### ISSUE TITLE
Allow user specify width and height of a dialog box?

### ISSUE THREAD

**Issue by tcdw** [131/whiptail#1]
I noticed sometimes the dialog box is too small to make my text displays properly (especially when using `textbox`).

I think if allow user specify width and height instead of 0 that hardcoded in the `index.js`, the problem will be solved smoothly, plus most users would use terminal with more than 80 characters wide.

Sorry for my bad English :(

**Comment by 131** [comment]
Sorry that i did not read your message earlier. I'm closing, feel free to re-open with a PR if you want
